matrix:
  include:
    language: crystal
    install:
      - shards install
    script:
      - crystal spec src/
      - crystal bin/ameba.cr

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crystal-data/num.cr
  on:
    branch: github-pages
  local_dir: docs
