matrix:
  include:
    language: crystal
    install:
      - shards install
    script:
      - crystal spec src/
      - crystal bin/ameba.cr

    language: python
    install:
      - pip install sphinx
    script:
      - make -C doc html
      - touch src/doc/_build/html/.nojekyll
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      project_name: bottle
      on:
        branch: master
      local_dir: src/doc/_build/html
