language: crystal
install:
  - shards install
script:
  - crystal spec
  - crystal bin/ameba.cr
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: bottle
  on:
    branch: master
  local_dir: docs
